name: Build
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOOLCHAIN_VERSION: "14.2.0-3"
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Toolchain
      id: cache-toolchain
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-toolchain-${{ env.TOOLCHAIN_VERSION }}
        path: toolchain/

    - name: Install ShellCheck
      run: |
        sudo apt-get update -y
        sudo apt-get install shellcheck -y

    - name: Lint Shell Scripts
      run: |
        shellcheck --shell=sh --exclude=SC2086 --norc ./build.sh
        shellcheck --shell=sh --exclude=SC2086 --norc ./setup_toolchain.sh

    - name: Setup Toolchain
      if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
      run: ./setup_toolchain.sh

    - name: Build
      run: |
        ./build.sh
        mv build build-debug
        ./build.sh clean
        ./build.sh release
        mv build build-release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        if-no-files-found: error
        path: |
          ./build-debug
          ./build-release
